CREATE TABLE jugador (
    id INT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    equipo VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    dorsal INT NOT NULL,
    edad INT,
    cedula VARCHAR(20) UNIQUE,
    nacionalidad VARCHAR(50),
    goles INT
);

SELECT * FROM JUGADOR;

CREATE SEQUENCE poo
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;

CREATE OR REPLACE TRIGGER r
  BEFORE INSERT ON jugador
  FOR EACH ROW
BEGIN
  SELECT poo.nextval
  INTO :NEW.id
  FROM dual;
END;
/

CREATE TABLESPACE poo
DATAFILE 
  'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\poo.DBF' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

-- TABLESPACE
CREATE USER pablo1
  IDENTIFIED BY pablo1
  DEFAULT TABLESPACE poo
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

-- 1 Role for HR 
GRANT RESOURCE TO pablo1;
ALTER USER pablo1 DEFAULT ROLE ALL;

-- 7 System Privileges for HR 
GRANT ALTER SESSION TO pablo1;
GRANT CREATE DATABASE LINK TO pablo1;
GRANT CREATE SEQUENCE TO pablo1;
GRANT CREATE SESSION TO pablo1;
GRANT CREATE SYNONYM TO pablo1;
GRANT CREATE VIEW TO pablo1;
GRANT UNLIMITED TABLESPACE TO pablo1;